In [28]:
import torch
import math

In [7]:
test = torch.tensor([
            [[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
             [0.8414709568023682, 0.5403022766113281, 0.3109835982322693, 0.9504152536392212, 0.0998334139585495,
              0.9950041770935059, 0.031617503613233566, 0.9995000958442688, 0.009999833069741726, 0.9999500513076782,
              0.0031622713431715965, 0.9999950528144836, 0.0009999998146668077, 0.999999463558197,
              0.0003162277862429619, 0.9999999403953552],
             [0.9092974066734314, -0.416146844625473, 0.5911270976066589, 0.8065783977508545, 0.19866931438446045,
              0.9800665378570557, 0.06320339441299438, 0.9980006217956543, 0.019998665899038315, 0.9997999668121338,
              0.006324511021375656, 0.9999799728393555, 0.001999998465180397, 0.9999980330467224, 0.0006324555142782629,
              0.9999998211860657],
             [0.14112000167369843, -0.9899924993515015, 0.8126488924026489, 0.5827536582946777, 0.29552018642425537,
              0.9553365707397461, 0.0947260856628418, 0.9955034255981445, 0.029995499178767204, 0.9995500445365906,
              0.009486687369644642, 0.9999549984931946, 0.002999995369464159, 0.9999955296516418, 0.0009486832423135638,
              0.9999995827674866],
             [-0.756802499294281, -0.6536436080932617, 0.9535807371139526, 0.30113744735717773, 0.3894183337688446,
              0.9210610389709473, 0.1261540651321411, 0.9920106530189514, 0.03998933359980583, 0.9992001056671143,
              0.012648769654333591, 0.9999200105667114, 0.00399998901411891, 0.9999920129776001, 0.001264910795725882,
              0.9999991655349731],
             [-0.9589242339134216, 0.28366217017173767, 0.9999465346336365, -0.010342338122427464, 0.4794255197048187,
              0.8775826096534729, 0.15745587646961212, 0.9875260591506958, 0.04997916519641876, 0.9987502694129944,
              0.01581072434782982, 0.999875009059906, 0.004999978933483362, 0.9999874830245972, 0.0015811382327228785,
              0.9999988079071045],
             [-0.279415488243103, 0.9601702690124512, 0.9471482038497925, -0.320796400308609, 0.5646424293518066,
              0.8253356218338013, 0.18860027194023132, 0.9820539355278015, 0.059964004904031754, 0.998200535774231,
              0.018972521647810936, 0.9998200535774231, 0.005999963730573654, 0.9999819993972778, 0.001897365553304553,
              0.9999982714653015],
             [0.6569865942001343, 0.7539022564888, 0.8004215955734253, -0.5994374752044678, 0.6442176103591919,
              0.7648422122001648, 0.21955609321594238, 0.9755998849868774, 0.06994284689426422, 0.9975509643554688,
              0.02213412895798683, 0.9997549653053284, 0.006999942008405924, 0.9999755024909973, 0.002213592641055584,
              0.999997615814209]],
            [[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
             [0.8414709568023682, 0.5403022766113281, 0.3109835982322693, 0.9504152536392212, 0.0998334139585495,
              0.9950041770935059, 0.031617503613233566, 0.9995000958442688, 0.009999833069741726, 0.9999500513076782,
              0.0031622713431715965, 0.9999950528144836, 0.0009999998146668077, 0.999999463558197,
              0.0003162277862429619, 0.9999999403953552],
             [0.9092974066734314, -0.416146844625473, 0.5911270976066589, 0.8065783977508545, 0.19866931438446045,
              0.9800665378570557, 0.06320339441299438, 0.9980006217956543, 0.019998665899038315, 0.9997999668121338,
              0.006324511021375656, 0.9999799728393555, 0.001999998465180397, 0.9999980330467224, 0.0006324555142782629,
              0.9999998211860657],
             [0.14112000167369843, -0.9899924993515015, 0.8126488924026489, 0.5827536582946777, 0.29552018642425537,
              0.9553365707397461, 0.0947260856628418, 0.9955034255981445, 0.029995499178767204, 0.9995500445365906,
              0.009486687369644642, 0.9999549984931946, 0.002999995369464159, 0.9999955296516418, 0.0009486832423135638,
              0.9999995827674866],
             [-0.756802499294281, -0.6536436080932617, 0.9535807371139526, 0.30113744735717773, 0.3894183337688446,
              0.9210610389709473, 0.1261540651321411, 0.9920106530189514, 0.03998933359980583, 0.9992001056671143,
              0.012648769654333591, 0.9999200105667114, 0.00399998901411891, 0.9999920129776001, 0.001264910795725882,
              0.9999991655349731],
             [-0.9589242339134216, 0.28366217017173767, 0.9999465346336365, -0.010342338122427464, 0.4794255197048187,
              0.8775826096534729, 0.15745587646961212, 0.9875260591506958, 0.04997916519641876, 0.9987502694129944,
              0.01581072434782982, 0.999875009059906, 0.004999978933483362, 0.9999874830245972, 0.0015811382327228785,
              0.9999988079071045],
             [-0.279415488243103, 0.9601702690124512, 0.9471482038497925, -0.320796400308609, 0.5646424293518066,
              0.8253356218338013, 0.18860027194023132, 0.9820539355278015, 0.059964004904031754, 0.998200535774231,
              0.018972521647810936, 0.9998200535774231, 0.005999963730573654, 0.9999819993972778, 0.001897365553304553,
              0.9999982714653015],
             [0.6569865942001343, 0.7539022564888, 0.8004215955734253, -0.5994374752044678, 0.6442176103591919,
              0.7648422122001648, 0.21955609321594238, 0.9755998849868774, 0.06994284689426422, 0.9975509643554688,
              0.02213412895798683, 0.9997549653053284, 0.006999942008405924, 0.9999755024909973, 0.002213592641055584,
              0.999997615814209]]
        ])
print(test.shape)


torch.Size([2, 8, 16])


In [14]:
position = torch.arange(0, 8).unsqe
position.shape


torch.Size([8])

In [16]:
embedding_dim = 16
div_term = torch.exp(torch.arange(0, embedding_dim, 2).float() * -(math.log(10000.0) / embedding_dim))
div_term

tensor([1.0000e+00, 3.1623e-01, 1.0000e-01, 3.1623e-02, 1.0000e-02, 3.1623e-03,
        1.0000e-03, 3.1623e-04])

In [27]:
div_terms = 1 / torch.pow(10000, torch.arange(0, embedding_dim, 2) / embedding_dim)
div_term


tensor([1.0000e+00, 3.1623e-01, 1.0000e-01, 3.1623e-02, 1.0000e-02, 3.1623e-03,
        1.0000e-03, 3.1623e-04])

In [25]:
torch.arange(0, embedding_dim//2)

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
torch.arange(0, embedding_dim, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [24]:
from modelling.attention import Attention
import torch

In [10]:
VALUE = torch.tensor([
    [[0.0349, 0.3211, 1.5736, -0.8455],
     [0.0000, 0.0000, 0.0000, 0.0000]],
    [[-1.4181, 0.8963, 0.0499, 2.2667],
     [1.1790, -0.4345, -1.3864, -1.2862]]
])

QUERY = torch.tensor([
    [[1.9269, 1.4873, 0.9007, -2.1055],
     [0.6784, -1.2345, -0.0431, -1.6047],
     [0.3559, -0.6866, -0.4934, 0.2415]],
    [[-1.1109, 0.0915, -2.3169, -0.2168],
     [-0.3097, -0.3957, 0.8034, -0.6216],
     [0.0000, 0.0000, 0.0000, 0.0000]]
])

QUERY_ATTENTION_MASK = torch.tensor([[1, 1, 1], [1, 1, 0]])
VALUE_ATTENTION_MASK = torch.tensor([[1, 0], [1, 1]])

ATTENTION_TEST_DATA = [
    (
        Attention(mask_future=False),
        QUERY,
        QUERY,
        QUERY_ATTENTION_MASK,
        torch.tensor([
            [[1.9050642251968384, 1.4421212673187256, 0.8837929368019104, -2.0934135913848877],
             [0.9809781312942505, -0.45746949315071106, 0.16625413298606873, -1.5649594068527222],
             [0.7208702564239502, -0.5859572887420654, -0.1027706041932106, -0.8587384223937988]],
            [[-1.0970195531845093, 0.08305942267179489, -2.2628417015075684, -0.2238130271434784],
             [-0.47443872690200806, -0.2955244183540344, 0.16181963682174683, -0.5383670330047607],
             [-0.7103000283241272, -0.15209999680519104, -0.7567499876022339, -0.41920000314712524]]
        ])
    ),
    (
        Attention(mask_future=True),
        QUERY,
        QUERY,
        QUERY_ATTENTION_MASK,
        torch.tensor([
            [[1.926900029182434, 1.4873000383377075, 0.9006999731063843, -2.1054999828338623],
             [1.0457112789154053, -0.4337407648563385, 0.23456794023513794, -1.7520363330841064],
             [0.7208702564239502, -0.5859572887420654, -0.1027706041932106, -0.8587384223937988]],
            [[-1.1109000444412231, 0.09149999916553497, -2.3169000148773193, -0.2168000042438507],
             [-0.47443872690200806, -0.2955244183540344, 0.16181963682174683, -0.5383670330047607],
             [-0.7103000283241272, -0.15209999680519104, -0.7567499876022339, -0.41920000314712524]]
        ])
    ),
    (
        Attention(mask_future=False),
        QUERY,
        VALUE,
        VALUE_ATTENTION_MASK,
        torch.tensor([
            [[0.0348999984562397, 0.32109999656677246, 1.5736000537872314, -0.8454999923706055],
             [0.0348999984562397, 0.32109999656677246, 1.5736000537872314, -0.8454999923706055],
             [0.0348999984562397, 0.32109999656677246, 1.5736000537872314, -0.8454999923706055]],
            [[0.22614431381225586, 0.0537601113319397, -0.8594327569007874, 0.017331182956695557],
             [0.12951618432998657, 0.10327407717704773, -0.8059935569763184, 0.14952099323272705],
             [-0.11954998970031738, 0.23090000450611115, -0.6682499647140503, 0.49024999141693115]]
        ])
    )
]

In [28]:
from modelling.attention import Attention

attn = Attention(mask_future=False)
out = attn(QUERY, VALUE, VALUE, VALUE_ATTENTION_MASK)